CREATE TABLE `CLIENTES` (
  `CPF` varchar(100) NOT NULL,
  `Nome` varchar(100) DEFAULT NULL,
  UNIQUE KEY `CPF` (`CPF`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
SELECT * FROM MEGALOCADORA.CLIENTES;